plugins {
    id 'java'
    id 'io.freefair.lombok' version '8.2.2'
//    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

//dependencies {
//    implementation fileTree(dir: '/Users/jooyeonjin/Desktop/GradProject_Apache_Kafka/execute/kafka_2.13-3.9.0/libs', include: ['*.jar'])
//    implementation 'org.apache.kafka:kafka-clients:3.9.0'
//
//    implementation 'info.picocli:picocli-codegen:4.7.4'
//    implementation 'org.slf4j:slf4j-api:2.0.7'
//    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.24.3'
//    implementation 'org.apache.logging.log4j:log4j-api:2.24.3'
//    implementation 'org.apache.logging.log4j:log4j-core:2.24.3'
//    implementation 'org.apache.poi:poi-ooxml:5.4.0'
//    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
//    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
//}
dependencies {
    implementation fileTree(dir: '/Users/jooyeonjin/Desktop/GradProject_Apache_Kafka/execute/kafka_2.13-3.9.0/libs', include: ['*.jar'])

    implementation 'org.apache.kafka:kafka-clients:3.9.0'
    implementation 'info.picocli:picocli-codegen:4.7.4'

    implementation 'org.slf4j:slf4j-api:2.0.7'
    implementation 'ch.qos.logback:logback-classic:1.4.11' // ✅ SLF4J 2.x 구현체

    implementation 'org.apache.logging.log4j:log4j-api:2.24.3'
    implementation 'org.apache.logging.log4j:log4j-core:2.24.3'

    implementation 'org.apache.poi:poi-ooxml:5.4.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    archiveBaseName.set('kafka-test-clients-fat')
    archiveVersion.set('1.0')
    archiveClassifier.set('')
}


test {
    useJUnitPlatform()
}